# Generated by Django 3.1.2 on 2022-02-26 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import saleor.utilities.time_utilities


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_auto_20200810_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instagram_username', models.CharField(blank=True, max_length=256)),
                ('instagram_user_id', models.CharField(blank=True, max_length=256)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('state', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('ig_status', models.BooleanField(default=False)),
                ('instagram_link', models.TextField(blank=True, null=True)),
                ('facebook_link', models.TextField(blank=True, null=True)),
                ('youtube_link', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('created_at',),
                'permissions': (('manage_influencer', 'Manage Influencer.'),),
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('mobile_no',), 'permissions': (('manage_users', 'Manage customers.'), ('manage_staff', 'Manage staff.'))},
        ),
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_no',
            field=models.TextField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='InfluencerUpiId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('upi_id', models.CharField(max_length=20)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upi_ids', to='account.influencer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InfluencerBankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('ac_name', models.CharField(max_length=128, verbose_name='Account Holder Name')),
                ('ac_number', models.CharField(max_length=32, verbose_name='Bank Account Number')),
                ('ac_bank_name', models.CharField(max_length=128, verbose_name='Bank Name')),
                ('ac_bank_branch', models.CharField(max_length=256, verbose_name='Bank Branch')),
                ('ac_ifsc_code', models.CharField(max_length=16, verbose_name='IFSC Code')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='account.influencer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='influencer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influencer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.TextField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(default=saleor.utilities.time_utilities.TimeUtilities.get_time_with_delta)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
