# Generated by Django 3.1.2 on 2022-03-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0048_auto_20220226_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerupiid',
            name='upi_id',
            field=models.CharField(max_length=128),
        ),
    ]
