# Generated by Django 3.1.2 on 2022-04-12 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0049_auto_20220311_1554'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='influencerbankaccount',
            unique_together={('ac_number', 'ac_ifsc_code')},
        ),
    ]
