# Generated by Django 3.1.2 on 2022-02-26 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import saleor.brand.models
import saleor.core.utils.json_serializer
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0048_auto_20220226_2147'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_metadata', models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=75)),
                ('brand_name', models.CharField(max_length=75, unique=True)),
                ('brand_contact_name', models.CharField(max_length=75)),
                ('brand_contact_number', models.CharField(blank=True, max_length=75)),
                ('active', models.BooleanField(default=False)),
                ('shipping_return_policy', models.JSONField(blank=True, default=saleor.brand.models.get_default_return_exchange_policy)),
                ('zaamo_creators_guidelines', models.JSONField(blank=True, default=dict)),
                ('short_description', models.CharField(blank=True, default='', max_length=300)),
                ('size_fit_note', models.CharField(blank=True, default='', max_length=300)),
                ('prefered_payment_mode', models.CharField(choices=[('bank account', 'Bank Account'), ('upi id', 'UPI ID')], default='bank account', max_length=25)),
                ('brand_source', models.CharField(choices=[('manual', 'manual'), ('shopify', 'shopify'), ('staff', 'staff'), ('woocommerce', 'woocommerce'), ('wix', 'wix')], default='staff', max_length=25)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='brands')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pan_number', models.CharField(blank=True, default='', max_length=10, verbose_name='PAN Number')),
                ('brand_order_info', models.TextField(blank=True, default='')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_address', to='account.address')),
                ('return_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_return_address', to='account.address')),
            ],
            options={
                'ordering': ['brand_name'],
            },
        ),
        migrations.CreateModel(
            name='StaffBrandMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_brand_mappings', to='brand.brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_brand_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commission_percentage', models.FloatField(default=0.0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='brand.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrandUpiId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('upi_id', models.CharField(max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upi_ids', to='brand.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrandShippingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home_state_pincode', models.CharField(blank=True, max_length=10)),
                ('country', django_countries.fields.CountryField(default='IN', max_length=2)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('shipping_cost_same_state_amount', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('shipping_cost_other_state_amount', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('min_order_value_free_cost_amount', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_shipping', to='brand.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrandEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_email', models.EmailField(blank=True, max_length=254)),
                ('state', models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary')], default='secondary', max_length=15)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_emails', to='brand.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrandBankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('ac_name', models.CharField(max_length=128, verbose_name='Account Holder Name')),
                ('ac_number', models.CharField(max_length=32, verbose_name='Bank Account Number')),
                ('ac_bank_name', models.CharField(max_length=128, verbose_name='Bank Name')),
                ('ac_bank_branch', models.CharField(max_length=256, verbose_name='Bank Branch')),
                ('ac_ifsc_code', models.CharField(max_length=16, verbose_name='IFSC Code')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='brand.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='staff_members',
            field=models.ManyToManyField(related_name='authourised_brands', through='brand.StaffBrandMapping', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BrandMemberState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('owner', 'owner'), ('staff', 'staff')], default='owner', max_length=25)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_member_states', to='brand.brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('brand', 'user')},
            },
        ),
    ]
