# Generated by Django 3.1.2 on 2022-02-28 18:01

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandGrouping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='brand/brand_grouping')),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrandGroupMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_group_rank', models.PositiveIntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='through_brand_group_mapping', to='brand.brand')),
                ('brand_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='through_brand_group_mapping', to='brand.brandgrouping')),
            ],
            options={
                'ordering': ('brand_group_rank', 'created_at'),
            },
        ),
        migrations.AddField(
            model_name='brandgrouping',
            name='brands',
            field=models.ManyToManyField(related_name='brand_grouping', through='brand.BrandGroupMapping', to='brand.Brand'),
        ),
    ]
