# Generated by Django 3.1.2 on 2022-03-06 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_auto_20220228_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandPayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('transaction_details', models.CharField(blank=True, max_length=500)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_payout', to='brand.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
