# Generated by Django 3.1.2 on 2022-03-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_brandpayout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandgrouping',
            options={'ordering': ('group_rank', '-created_at')},
        ),
        migrations.AlterModelOptions(
            name='brandgroupmapping',
            options={'ordering': ('brand_group_rank', '-created_at')},
        ),
        migrations.AddField(
            model_name='brandgrouping',
            name='group_rank',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='brandmemberstate',
            name='state',
            field=models.CharField(choices=[('owner', 'owner'), ('staff', 'staff'), ('in-active', 'in-active')], default='owner', max_length=25),
        ),
    ]
