# Generated by Django 3.1.2 on 2022-03-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0005_auto_20220311_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandpayout',
            name='mode_of_payment',
            field=models.CharField(blank=True, choices=[('upi', 'Upi'), ('neft/imps', 'Neft/Imps')], max_length=15),
        ),
    ]
