# Generated by Django 3.1.2 on 2022-03-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0006_brandpayout_mode_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='order_processing_days',
            field=models.SmallIntegerField(default=0),
        ),
    ]
