# Generated by Django 3.1.2 on 2022-03-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0007_brand_order_processing_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandemail',
            name='state',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('support', 'support')], default='secondary', max_length=15),
        ),
    ]
