# Generated by Django 3.1.2 on 2022-04-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0008_auto_20220331_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='order_shipping_days',
            field=models.SmallIntegerField(default=0),
        ),
    ]
