# Generated by Django 3.1.2 on 2022-04-12 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0009_brand_order_shipping_days'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brandbankaccount',
            unique_together={('ac_number', 'ac_ifsc_code')},
        ),
    ]
