# Generated by Django 3.1.2 on 2022-04-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0010_auto_20220412_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='botd',
            field=models.BooleanField(default=False, help_text='If marked true then this can be made Brand Of The Day'),
        ),
    ]
