# Generated by Django 3.1.2 on 2022-04-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0011_brand_botd'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_barter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_barter_guidelines',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
