# Generated by Django 3.1.2 on 2022-04-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0012_auto_20220427_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='too_many_orders',
            field=models.BooleanField(default=False),
        ),
    ]
