# Generated by Django 3.1.2 on 2022-05-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0013_brand_too_many_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_source',
            field=models.CharField(choices=[('manual', 'manual'), ('shopify', 'shopify'), ('staff', 'staff'), ('woocommerce', 'woocommerce'), ('wix', 'wix'), ('achaindia', 'achaindia')], default='staff', max_length=25),
        ),
    ]
