# Generated by Django 3.1.2 on 2022-05-19 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0141_auto_20220518_1536'),
        ('brand', '0014_auto_20220517_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=240)),
                ('type', models.CharField(choices=[('collection', 'collection'), ('category', 'category')], default='collection', max_length=25)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_collection', to='brand.brand')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='BrandCollectionMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='through_brand_collection', to='brand.brandcollection')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='through_brand_collection_product', to='product.product')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.AddField(
            model_name='brandcollection',
            name='product',
            field=models.ManyToManyField(through='brand.BrandCollectionMapping', to='product.Product'),
        ),
    ]
