# Generated by Django 3.1.2 on 2022-05-27 13:49

from django.db import migrations, models
import saleor.core.utils.json_serializer


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0015_auto_20220519_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandcollection',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='brandcollection',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True),
        ),
        migrations.AddField(
            model_name='brandcollection',
            name='private_metadata',
            field=models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True),
        ),
    ]
