# Generated by Django 3.1.2 on 2022-06-10 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20220610_1328'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brand', '0016_auto_20220527_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrear_details', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('arrear_type', models.CharField(choices=[('Influencer', 'Influencer'), ('Brand', 'Brand')], default='Brand', max_length=50)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brand.brand')),
                ('person_of_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.storeinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
