# Generated by Django 3.1.2 on 2022-06-11 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0017_arrear'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandCred',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_key', models.CharField(max_length=240)),
                ('access_pass', models.CharField(max_length=240)),
                ('auth_token', models.CharField(blank=True, max_length=240, null=True)),
                ('url', models.CharField(max_length=300)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
