# Generated by Django 3.1.2 on 2022-06-14 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brand', '0018_brandcred'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('active only for barter', 'active only for barter')], default='inactive', max_length=75),
        ),
        migrations.AddField(
            model_name='brand',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
