# Generated by Django 3.1.2 on 2022-06-23 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0019_auto_20220614_1347'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brandgroupmapping',
            unique_together={('brand', 'brand_group')},
        ),
    ]
