# Generated by Django 3.1.2 on 2022-02-26 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0132_auto_20220226_2147'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('brand', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffStoreMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_name', models.CharField(blank=True, max_length=512)),
                ('store_url', models.TextField(null=True)),
                ('description', models.JSONField(default=dict)),
                ('state', models.IntegerField(default=1)),
                ('slug', models.SlugField(max_length=512, unique=True)),
                ('store_type', models.CharField(choices=[('brand', 'brand'), ('influencer', 'influencer')], default='influencer', max_length=15)),
                ('store_category_page_level', models.CharField(choices=[('level_1', 'level_1'), ('level_2', 'level_2')], default='level_2', max_length=32)),
                ('staff_members', models.ManyToManyField(related_name='authourised_stores', through='store.StaffStoreMapping', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='StoreTile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.CharField(max_length=128, null=True)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='store_tiles')),
                ('rank', models.IntegerField(default=0)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('tile_type', models.CharField(choices=[('influencer_home', 'influencer_home'), ('influencer_store', 'influencer_store'), ('influencer_home_store', 'influencer_home_store')], default='influencer_store', max_length=32)),
                ('stores', models.ManyToManyField(related_name='store_tiles', to='store.StoreInfo')),
            ],
            options={
                'ordering': ('rank', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='StoreNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('image_url', models.TextField()),
                ('route', models.TextField(null=True)),
                ('stores', models.ManyToManyField(related_name='notifications', to='store.StoreInfo')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='StoreCategoryPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_added', models.BooleanField(db_index=True, default=False)),
                ('add_count', models.IntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_category_page', to='brand.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_category_page', to='product.category')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_category_page', to='store.storeinfo')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='staffstoremapping',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_store_mappings', to='store.storeinfo'),
        ),
        migrations.AddField(
            model_name='staffstoremapping',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_store_mappings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StoreMemberState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('state', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this Member state belongs to. A user will get all permissionsgranted to each of their groups.', related_name='storemember_set', related_query_name='storemember', to='auth.Group', verbose_name='groups')),
                ('member_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='storemember_set', related_query_name='storemember', to='auth.Permission', verbose_name='store permissions')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_members', to='store.storeinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('store', 'user')},
            },
        ),
    ]
