# Generated by Django 3.1.2 on 2022-03-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_storepayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='storepayout',
            name='modeofpayment',
            field=models.CharField(blank=True, choices=[('upi', 'Upi'), ('neft/imps', 'Neft/Imps')], max_length=15),
        ),
    ]
