# Generated by Django 3.1.2 on 2022-04-04 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_storepayout_modeofpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreManagerComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='store.storeinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='StoreManagerActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACCESS_APPROVED', 'ACCESS_APPROVED'), ('KEEN_TO_TRY', 'KEEN_TO_TRY'), ('BARTER_INITATED', 'BARTER_INITATED'), ('HAPPY_WITH_INITIAL_RESPONSE', 'HAPPY_WITH_INITIAL_RESPONSE'), ('TRIED_BUT_NOT_GOOD_RESPONSE', 'TRIED_BUT_NOT_GOOD_RESPONSE')], default='ACCESS_APPROVED', max_length=32)),
                ('next_actions', models.CharField(choices=[('GIVE_DISCOUNTS', 'GIVE_DISCOUNTS'), ('GIVE_BARTER', 'GIVE_BARTER'), ('HAND_HOLD_IN_MAKING_THE_STORE', 'HAND_HOLD_IN_MAKING_THE_STORE'), ('ASK_TO_TRY_MORE_ACTIVELY', 'ASK_TO_TRY_MORE_ACTIVELY')], default='GIVE_DISCOUNTS', max_length=32)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='store.storeinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
