# Generated by Django 3.1.2 on 2022-04-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_storemanageractions_storemanagercomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemanageractions',
            name='status',
            field=models.CharField(choices=[('ACCESS_APPROVED', 'ACCESS_APPROVED'), ('KEEN_TO_TRY', 'KEEN_TO_TRY'), ('BARTER_INITIATED', 'BARTER_INITIATED'), ('HAPPY_WITH_INITIAL_RESPONSE', 'HAPPY_WITH_INITIAL_RESPONSE'), ('TRIED_BUT_NOT_GOOD_RESPONSE', 'TRIED_BUT_NOT_GOOD_RESPONSE')], default='ACCESS_APPROVED', max_length=32),
        ),
    ]
