# Generated by Django 3.1.2 on 2022-04-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20220412_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemanageractions',
            name='next_actions',
            field=models.CharField(choices=[('GIVE_DISCOUNTS', 'GIVE_DISCOUNTS'), ('GIVE_BARTER', 'GIVE_BARTER'), ('HAND_HOLD_IN_MAKING_THE_STORE', 'HAND_HOLD_IN_MAKING_THE_STORE'), ('ASK_TO_TRY_MORE_ACTIVELY', 'ASK_TO_TRY_MORE_ACTIVELY'), ('WAIT', 'WAIT')], default='GIVE_DISCOUNTS', max_length=50),
        ),
        migrations.AlterField(
            model_name='storemanageractions',
            name='status',
            field=models.CharField(choices=[('TEST_STORE', 'TEST_STORE'), ('STILL_EXPLORING', 'STILL_EXPLORING'), ('BARTER_IN_PROCESS', 'BARTER_IN_PROCESS'), ('A1_STORE_WORKING', 'A1_STORE_WORKING'), ('A1_STORE_JUST_STARTED', 'A1_STORE_JUST_STARTED'), ('A1_STORE_ENTHU_NO_SALES_RECENTLY', 'A1_STORE_ENTHU_NO_SALES_RECENTLY'), ('A1_OWN_PACE', 'A1_OWN_PACE'), ('A1_ONLY_KEEN_ON_SOURCING_NO_STORE_ENTHU', 'A1_ONLY_KEEN_ON_SOURCING_NO_STORE_ENTHU'), ('A2_STORE_ENTHU', 'A2_STORE_ENTHU'), ('A2_OWN_PACE', 'A2_OWN_PACE'), ('A2_SOURCING_ENTHU', 'A2_SOURCING_ENTHU'), ('B1_STORE_ENTHU', 'B1_STORE_ENTHU'), ('B1_SOURCING_ENTHU', 'B1_SOURCING_ENTHU'), ('INACTIVE_ON_INSTAGRAM', 'INACTIVE_ON_INSTAGRAM'), ('BAD_ZAAMO_EXPERIENCE', 'BAD_ZAAMO_EXPERIENCE'), ('UNABLE_TO_CONNECT_ON_CALL_OR_TEXT', 'UNABLE_TO_CONNECT_ON_CALL_OR_TEXT'), ('NOT_INTRESTED_TO_CONTINUE', 'NOT_INTRESTED_TO_CONTINUE')], default='STILL_EXPLORING', max_length=50),
        ),
    ]
