# Generated by Django 3.1.2 on 2022-05-23 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20220428_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_orders', models.IntegerField(default=0)),
                ('wishlist_of_products', models.IntegerField(default=0)),
                ('no_of_sourcing_requests_initiated', models.IntegerField(default=0)),
                ('no_of_sourcing_requests_brand_fullfilled', models.IntegerField(default=0)),
                ('number_of_products_sold', models.IntegerField(default=0)),
                ('total_store_sales', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_store_sales_after_discount', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_msp_sales', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('analytics_date', models.DateTimeField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_analytics', to='store.storeinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
