# Generated by Django 3.1.2 on 2022-06-08 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brand', '0016_auto_20220527_1349'),
        ('store', '0008_auto_20220528_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandSourcingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('terms_and_conditions', models.TextField()),
                ('store_bucket', models.CharField(choices=[('TEST_STORE', 'TEST_STORE'), ('STILL_EXPLORING', 'STILL_EXPLORING'), ('BARTER_IN_PROCESS', 'BARTER_IN_PROCESS'), ('A1_STORE_WORKING', 'A1_STORE_WORKING'), ('A1_STORE_JUST_STARTED', 'A1_STORE_JUST_STARTED'), ('A1_STORE_ENTHU_NO_SALES_RECENTLY', 'A1_STORE_ENTHU_NO_SALES_RECENTLY'), ('A1_OWN_PACE', 'A1_OWN_PACE'), ('A1_ONLY_KEEN_ON_SOURCING_NO_STORE_ENTHU', 'A1_ONLY_KEEN_ON_SOURCING_NO_STORE_ENTHU'), ('A2_STORE_ENTHU', 'A2_STORE_ENTHU'), ('A2_OWN_PACE', 'A2_OWN_PACE'), ('A2_SOURCING_ENTHU', 'A2_SOURCING_ENTHU'), ('B1_STORE_ENTHU', 'B1_STORE_ENTHU'), ('B1_SOURCING_ENTHU', 'B1_SOURCING_ENTHU'), ('INACTIVE_ON_INSTAGRAM', 'INACTIVE_ON_INSTAGRAM'), ('BAD_ZAAMO_EXPERIENCE', 'BAD_ZAAMO_EXPERIENCE'), ('UNABLE_TO_CONNECT_ON_CALL_OR_TEXT', 'UNABLE_TO_CONNECT_ON_CALL_OR_TEXT'), ('NOT_INTRESTED_TO_CONTINUE', 'NOT_INTRESTED_TO_CONTINUE'), ('PASS_ON', 'PASS_ON')], default='STILL_EXPLORING', max_length=50)),
                ('state', models.CharField(choices=[('REQUEST_RECEIVED', 'REQUEST_RECEIVED'), ('ACCEPT', 'ACCEPT'), ('REJECT', 'REJECT')], default='REQUEST_RECEIVED', max_length=20)),
                ('brand_managers', models.TextField(null=True)),
                ('store_managers', models.TextField(null=True)),
                ('brand_collab', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.brand')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.storeinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
