# Generated by Django 3.1.2 on 2022-06-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20220616_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandsourcingrequest',
            name='campaign_name',
            field=models.TextField(null=True),
        ),
    ]
