# Generated by Django 3.1.2 on 2022-02-26 21:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import saleor.product.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
        ('product', '0131_update_ts_vector_existing_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandVariantZaamoMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_id_brand', models.CharField(blank=True, max_length=255, null=True)),
                ('sku_id_brand', models.CharField(blank=True, max_length=255, null=True)),
                ('variant_id_brand', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandingPageCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('category_rank', models.PositiveIntegerField(default=0)),
                ('category', models.OneToOneField(limit_choices_to={'parent_id': None}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_category', to='product.category')),
            ],
            options={
                'ordering': ('category_rank', 'created_at'),
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='image_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='is_thrift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='media_type',
            field=models.TextField(default='image'),
        ),
        migrations.AddField(
            model_name='collection',
            name='shop_look',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='brand.brand'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to=saleor.product.models.upload_to_product),
        ),
        migrations.CreateModel(
            name='LandingPageSubCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sub_category_rank', models.PositiveIntegerField(default=0)),
                ('landing_page_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='through_landing_page_category', to='product.landingpagecategories')),
                ('sub_category', models.ForeignKey(limit_choices_to={'parent__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='through_landing_page_subcategory', to='product.category')),
            ],
            options={
                'ordering': ('sub_category_rank', 'created_at'),
            },
        ),
        migrations.AddField(
            model_name='landingpagecategories',
            name='sub_categories',
            field=models.ManyToManyField(related_name='sub_categories', through='product.LandingPageSubCategories', to='product.Category'),
        ),
        migrations.CreateModel(
            name='CollectionStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_store', to='product.collection')),
            ],
        ),
    ]
