# Generated by Django 3.1.2 on 2022-02-26 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0132_auto_20220226_2147'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionstore',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_store', to='store.storeinfo'),
        ),
        migrations.AddField(
            model_name='collectionstore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_store', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brandvariantzaamomapping',
            name='product_zaamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='brandvariantzaamomapping',
            name='variant_zaamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='collectionstore',
            unique_together={('collection', 'store')},
        ),
    ]
