# Generated by Django 3.1.2 on 2022-03-23 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0133_auto_20220226_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
