# Generated by Django 3.1.2 on 2022-03-29 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_storepayout_modeofpayment'),
        ('product', '0134_collectionproduct_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProductViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.storeinfo')),
            ],
        ),
    ]
