# Generated by Django 3.1.2 on 2022-04-12 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0010_auto_20220412_1607'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0005_auto_20220412_1607'),
        ('product', '0135_storeproductviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourcingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('influencer_managers', models.TextField(null=True)),
                ('brand_managers', models.TextField(null=True)),
                ('status', models.CharField(choices=[('request received', 'Request Received'), ('brand contact for sourcing', 'Brand Contact For Sourcing'), ('brand will contact the influencer', 'Brand Will Contact the Influencer'), ('brand collaboration approved', 'Brand Collaboration Approved'), ('brand coupon created', 'Brand Coupon Created'), ('brand not interested', 'Brand Not Interested'), ('zaamo will fulfill request', 'Zaamo Will Fulfill Request'), ('zaamo coupon created', 'Zaamo Coupon Created'), ('zaamo not interested', 'Zaamo Not Interested'), ('influencer content created', 'Influencer Content Created'), ('product exchange or return requested', 'Product exchange or return Requested'), ('request cancelled by influencer', 'Request Cancelled By Influencer')], default='request received', max_length=100)),
                ('content', models.TextField(null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sourcing', to='brand.brand')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sourcing', to='product.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sourcing', to='store.storeinfo')),
                ('user_last_updated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sourcing', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sourcing', to='product.productvariant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
