# Generated by Django 3.1.2 on 2022-04-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0136_sourcingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='commission_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='has_custom_commission',
            field=models.BooleanField(default=False),
        ),
    ]
