# Generated by Django 3.1.2 on 2022-04-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0137_auto_20220425_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_barter',
            field=models.BooleanField(default=False),
        ),
    ]
