# Generated by Django 3.1.2 on 2022-04-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0138_product_brand_barter'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandPriceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_id_brand', models.CharField(blank=True, max_length=255, null=True)),
                ('variant_id_brand', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=225, null=True)),
                ('current_price_amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('current_cost_price_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('prev_price_amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('prev_cost_price_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
