# Generated by Django 3.1.2 on 2022-05-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0139_brandpricerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandpricerecord',
            name='data_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='brandpricerecord',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brandpricerecord',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='brandpricerecord',
            name='variant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
