# Generated by Django 3.1.2 on 2022-05-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0140_auto_20220503_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcingrequest',
            name='status',
            field=models.CharField(choices=[('request received', 'Request Received'), ('brand contact for sourcing', 'Brand Contact For Sourcing'), ('brand will contact the influencer', 'Brand Will Contact the Influencer'), ('brand collaboration approved', 'Brand Collaboration Approved'), ('brand coupon created', 'Brand Coupon Created'), ('brand not interested', 'Brand Not Interested'), ('zaamo will fulfill request', 'Zaamo Will Fulfill Request'), ('zaamo coupon created', 'Zaamo Coupon Created'), ('zaamo not interested', 'Zaamo Not Interested'), ('influencer content created for Zaamo', 'Influencer Content Created For Zaamo'), ('influencer content created for Brand', 'Influencer Content Created For Brand'), ('product exchange or return requested', 'Product exchange or return Requested'), ('request cancelled by influencer', 'Request Cancelled By Influencer')], default='request received', max_length=100),
        ),
    ]
