# Generated by Django 3.1.2 on 2022-05-25 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0015_auto_20220519_1926'),
        ('product', '0141_auto_20220518_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandvariantzaamomapping',
            name='brand_zaamo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brand.brand'),
        ),
    ]
