# Generated by Django 3.1.2 on 2022-05-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0142_brandvariantzaamomapping_brand_zaamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='ideas',
            field=models.BooleanField(default=False),
        ),
    ]
