# Generated by Django 3.1.2 on 2022-06-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0143_collection_ideas'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcingrequest',
            name='brand_collab',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO'), ('NA', 'NA')], default='NA', max_length=20),
        ),
    ]
