# Generated by Django 3.1.2 on 2022-06-23 16:52

from django.db import migrations, models
import django.db.models.deletion
import saleor.core.utils.json_serializer


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0020_auto_20220623_1652'),
        ('product', '0145_auto_20220616_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_metadata', models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=240)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.AlterField(
            model_name='sourcingrequest',
            name='status',
            field=models.CharField(choices=[('request received', 'Request Received'), ('brand shared deliverables', 'Brand Shared Deliverables'), ('brand will contact the influencer', 'Brand Will Contact the Influencer'), ('brand collaboration approved', 'Brand Collaboration Approved'), ('brand coupon created', 'Brand Coupon Created'), ('brand not interested', 'Brand Not Interested'), ('zaamo will fulfill request', 'Zaamo Will Fulfill Request'), ('zaamo coupon created', 'Zaamo Coupon Created'), ('zaamo not interested', 'Zaamo Not Interested'), ('influencer content created for Zaamo', 'Influencer Content Created For Zaamo'), ('influencer content created for Brand', 'Influencer Content Created For Brand'), ('product exchange or return requested', 'Product exchange or return Requested'), ('request cancelled by influencer', 'Request Cancelled By Influencer'), ('brand coupon clubbed', 'Brand Coupon Clubbed'), ('influencer hold', 'Influencer Hold'), ('brand hold', 'Brand Hold')], default='request received', max_length=100),
        ),
        migrations.CreateModel(
            name='ProductTagMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight', models.IntegerField(default=0)),
                ('source', models.CharField(choices=[('manual', 'manual'), ('name', 'name'), ('brandtag', 'brandtag'), ('description', 'description')], default='manual', max_length=25)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='through_product_tag_brand', to='brand.brand')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='through_product_tag_product', to='product.product')),
                ('product_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='through_product_tag', to='product.producttag')),
            ],
            options={
                'ordering': ('-updated_at',),
                'unique_together': {('product_tag', 'product')},
            },
        ),
        migrations.AddField(
            model_name='producttag',
            name='product',
            field=models.ManyToManyField(through='product.ProductTagMapping', to='product.Product'),
        ),
    ]
