# Generated by Django 3.1.2 on 2022-03-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0022_auto_20220226_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='is_shipping',
            field=models.BooleanField(default=False),
        ),
    ]
