# Generated by Django 3.1.2 on 2022-05-17 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20220428_1946'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discount', '0023_voucher_is_shipping'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voucher_code', models.CharField(default='', max_length=80)),
                ('log_msg', models.TextField(default='', max_length=400)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_logs', to='store.storeinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
