# Generated by Django 3.1.2 on 2022-06-16 13:09

from django.db import migrations, models
import django.db.models.deletion
import saleor.account.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0011_auto_20220616_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField()),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TestSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        )
    ]
