# Generated by Django 3.1.2 on 2022-06-16 13:13

from django.db import migrations, models
import django.db.models.deletion
import saleor.account.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20220616_1309'),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportQueries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', saleor.account.models.PossiblePhoneNumberField(blank=True, max_length=15, region=None)),
                ('message', models.TextField()),
                ('resolve_status', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_queries', to='store.storeinfo')),
            ],
            options={
                'ordering': ('updated_at',),
            },
        ),
    ]
