# Generated by Django 3.1.2 on 2022-06-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_delete_testsupport'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
