# Generated by Django 3.1.2 on 2022-02-26 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('checkout', '0029_auto_20200904_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CheckoutStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.storeinfo')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.checkout')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
