# Generated by Django 3.1.2 on 2022-03-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0030_auto_20220226_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='platform_code',
            field=models.CharField(choices=[('IS', 'IS'), ('IH', 'IH'), ('BH', 'BH'), ('ZS', 'ZS'), ('TP', 'TP'), ('AN', 'AN')], default='IS', max_length=32),
        ),
    ]
