# Generated by Django 3.1.2 on 2022-02-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0020_auto_20200902_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_office_name', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=10)),
            ],
        ),
    ]
