# Generated by Django 3.1.2 on 2022-07-05 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import functools
import saleor.notifications.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppNotificationTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Template Name')),
                ('code', models.SlugField(max_length=200)),
                ('message_type', models.IntegerField(choices=[(5, 'No Media'), (1, 'Image'), (3, 'Video'), (6, 'Gif'), (7, 'Carousel')], default=5)),
                ('thumbnail', models.FileField(blank=True, help_text='Valid formats - IMAGE : ( png / jpg / jpeg)', max_length=1280, null=True, upload_to=functools.partial(saleor.notifications.utils.media_file_path, *(), **{'media_folder_name': 'app_notifications_files/thumbnail/'}), validators=[functools.partial(saleor.notifications.utils.media_file_extension_validator, *(), **{'valid_extensions_file': ('jpg', 'jpeg', 'png')})], verbose_name='thumbnail')),
                ('media_file', models.FileField(blank=True, help_text='Valid formats - IMAGE : ( png / jpg / jpeg), VIDEO : ( mp4 / avi / mov), GIF : (gif)', max_length=1280, null=True, upload_to=functools.partial(saleor.notifications.utils.media_file_path, *(), **{'media_folder_name': 'app_notifications_files'}), validators=[functools.partial(saleor.notifications.utils.media_file_extension_validator, *(), **{'valid_extensions_file': ('jpg', 'jpeg', 'png', 'mp4', 'avi', 'mov', 'gif')})], verbose_name='Media File')),
                ('description', models.CharField(max_length=300, verbose_name='Template Description')),
                ('is_persistent', models.BooleanField(default=False, help_text='If True, Notification would stay persistent in Mobile App till Expiry Timestamp.', verbose_name='Is Persistent')),
                ('expiry_timestamp', models.DateTimeField(blank=True, help_text='Date after persistent notification will be removed from User App', null=True, verbose_name='Persistent Notification Expiry Date')),
                ('expiry_days', models.IntegerField(blank=True, help_text='No. of Days after persistent notification will be removed from User App', null=True, verbose_name='Persistent Notification Expiry Days')),
                ('onclick_action', models.CharField(blank=True, help_text='on tap land on a screen or website', max_length=255, null=True)),
                ('title', models.CharField(help_text='Title of your Notification template', max_length=255, verbose_name='Title')),
                ('body', models.TextField(blank=True, help_text='Define the text content of your template', null=True, verbose_name='Body')),
                ('template_type', models.CharField(choices=[('Campaign Based', 'Campaign Based'), ('Event Based', 'Event Based')], default='Event Based', max_length=30)),
            ],
            options={
                'verbose_name': 'App Notification Template',
                'verbose_name_plural': 'App Notification Templates',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(help_text='Title of Message')),
                ('onclick_action', models.TextField(blank=True, help_text='on tap land on a screen or website', null=True)),
                ('unread', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, help_text='Display Message', null=True)),
                ('expiry_timestamp', models.DateTimeField(blank=True, help_text='expiry datetime of the notification', null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-expiry_timestamp'),
            },
        ),
        migrations.CreateModel(
            name='MediaFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_type', models.IntegerField(choices=[(5, 'No Media'), (1, 'Image'), (3, 'Video'), (6, 'Gif'), (7, 'Carousel')], default=1, verbose_name='Media Type')),
                ('media_file', models.FileField(help_text='Valid formats - IMAGE : ( png / jpg / jpeg)', max_length=1280, upload_to=functools.partial(saleor.notifications.utils.media_file_path, *(), **{'file_type_identifier': 'media_type', 'media_folder_name': 'app_notifications_files'}), validators=[functools.partial(saleor.notifications.utils.media_file_extension_validator, *(), **{'valid_extensions_file': ('jpg', 'jpeg', 'png')})], verbose_name='Media File')),
                ('click_action', models.URLField(blank=True, null=True)),
                ('is_clickable', models.BooleanField(default=False)),
                ('app_notification_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='notifications.appnotificationtemplates')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('app_notification_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.appnotificationtemplates')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_version', models.FloatField(blank=True, help_text='Installed App Vesion On Mobile', null=True)),
                ('model', models.CharField(blank=True, help_text='Device Model Number', max_length=80, null=True)),
                ('manufacturer', models.CharField(blank=True, help_text='Device Manufacturer', max_length=255, null=True)),
                ('os_version', models.CharField(blank=True, help_text='Device OS Version', max_length=30, null=True)),
                ('device_type', models.CharField(choices=[('ios', 'Ios'), ('android', 'Android'), ('web', 'Web')], help_text='Different Type Of device type like Ios, Android, Web etc.', max_length=30)),
                ('fcm_id', models.TextField(default=None, help_text='fcm Id.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive devices will not be sent notifications')),
                ('app_installed_at', models.DateTimeField(blank=True, help_text='App Installation Time', null=True)),
                ('app_uninstalled_at', models.DateTimeField(blank=True, help_text='App Uninstall Time', null=True)),
                ('app_last_launched_at', models.DateTimeField(blank=True, help_text='App Launch Time', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'fcm_id')},
            },
        ),
    ]
