# Generated by Django 3.1.2 on 2022-02-26 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('brand', '0001_initial'),
        ('order', '0089_auto_20200902_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='brand.brand'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='commission_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='fulfillment',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('in process', 'In Process'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('return requested', 'Return Requested'), ('return initiated', 'Return Initiated'), ('return completed', 'Return Completed'), ('fulfilled', 'Fulfilled')], default='fulfilled', max_length=32),
        ),
        migrations.CreateModel(
            name='ShippingFulfillment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_id', models.CharField(max_length=100)),
                ('shipping_provider', models.CharField(max_length=100, null=True)),
                ('fulfillment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.fulfillment')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_store', to='order.order')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.storeinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
