# Generated by Django 3.1.2 on 2022-03-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0090_auto_20220226_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='shipping_cost_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
