# Generated by Django 3.1.2 on 2022-03-07 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0004_auto_20220307_1134'),
        ('order', '0091_orderline_shipping_cost_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBrandZaamoMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('order_id_brand', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.brand')),
                ('order_line_zaamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orderline')),
                ('order_zaamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
