# Generated by Django 3.1.2 on 2022-03-10 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0092_orderbrandzaamomapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulfillmentline',
            name='order_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_line', to='order.orderline'),
        ),
    ]
