# Generated by Django 3.1.2 on 2022-03-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0093_auto_20220310_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='platform_code',
            field=models.CharField(choices=[('IS', 'IS'), ('IH', 'IH'), ('BH', 'BH'), ('ZS', 'ZS'), ('TP', 'TP'), ('AN', 'AN')], default='IS', max_length=32),
        ),
        migrations.AlterField(
            model_name='fulfillment',
            name='status',
            field=models.CharField(choices=[('placed', 'Placed'), ('in process', 'In Process'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('return requested', 'Return Requested'), ('return initiated', 'Return Initiated'), ('return completed', 'Return Completed'), ('fulfilled', 'Fulfilled')], default='fulfilled', max_length=32),
        ),
    ]
