# Generated by Django 3.1.2 on 2022-03-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0094_auto_20220322_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulfillment',
            name='status',
            field=models.CharField(choices=[('placed', 'Placed'), ('in process', 'In Process'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancellation initiated', 'Cancellation Initiated'), ('cancellation processed', 'Cancellation Processed'), ('return requested', 'Return Requested'), ('return initiated', 'Return Initiated'), ('return completed', 'Return Completed'), ('fulfilled', 'Fulfilled')], default='fulfilled', max_length=32),
        ),
    ]
