# Generated by Django 3.1.2 on 2022-04-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0095_auto_20220329_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfillment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
