# Generated by Django 3.1.2 on 2022-04-27 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20220412_1607'),
        ('order', '0096_fulfillment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstore',
            name='streak_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderstore',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_store', to='store.storeinfo'),
        ),
    ]
