# Generated by Django 3.1.2 on 2022-05-19 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0098_auto_20220506_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
